"""agregar tabla mediciones

Revision ID: 0f5e814c8adf
Revises: 7a6920000c12
Create Date: 2026-07-28 01:39:09.670216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5e814c8adf'
down_revision: Union[str, None] = '7a6920000c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('altura', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('imc', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('pecho', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cintura', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cadera', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('brazo_derecho', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('brazo_izquierdo', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('muslo_derecho', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('muslo_izquierdo', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gemelo_derecho', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gemelo_izquierdo', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediciones_id'), 'mediciones', ['id'], unique=False)
    op.create_index(op.f('ix_mediciones_socio_id'), 'mediciones', ['socio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediciones_socio_id'), table_name='mediciones')
    op.drop_index(op.f('ix_mediciones_id'), table_name='mediciones')
    op.drop_table('mediciones')
    # ### end Alembic commands ###