"""agregar split, dias por semana y enfasis a mediciones

Revision ID: 238d4a620887
Revises: 76a8ebfed9c7
Create Date: 2026-08-11 20:22:47.204906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238d4a620887'
down_revision: Union[str, None] = '76a8ebfed9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediciones', sa.Column('split', sa.String(length=20), nullable=True))
    op.add_column('mediciones', sa.Column('dias_por_semana', sa.Integer(), nullable=True))
    op.add_column('mediciones', sa.Column('enfasis', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediciones', 'enfasis')
    op.drop_column('mediciones', 'dias_por_semana')
    op.drop_column('mediciones', 'split')
    # ### end Alembic commands ###