"""agregar stock minimo a productos

Revision ID: 6d3064f6b4cf
Revises: 47377fb498f2
Create Date: 2026-08-13 17:27:49.899300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3064f6b4cf'
down_revision: Union[str, None] = '47377fb498f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock_minimo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'stock_minimo')
    # ### end Alembic commands ###