"""agregar objetivo, nivel y biblioteca de ejercicios

Revision ID: 76a8ebfed9c7
Revises: c1410b78f1ce
Create Date: 2026-08-11 08:51:57.724678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a8ebfed9c7'
down_revision: Union[str, None] = 'c1410b78f1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('musculo', sa.String(length=40), nullable=False),
    sa.Column('equipo', sa.String(length=30), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('gif_url', sa.String(length=500), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejercicios_id'), 'ejercicios', ['id'], unique=False)
    op.create_index(op.f('ix_ejercicios_musculo'), 'ejercicios', ['musculo'], unique=False)
    op.create_index(op.f('ix_ejercicios_slug'), 'ejercicios', ['slug'], unique=True)
    op.add_column('mediciones', sa.Column('objetivo', sa.String(length=30), nullable=True))
    op.add_column('mediciones', sa.Column('nivel', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediciones', 'nivel')
    op.drop_column('mediciones', 'objetivo')
    op.drop_index(op.f('ix_ejercicios_slug'), table_name='ejercicios')
    op.drop_index(op.f('ix_ejercicios_musculo'), table_name='ejercicios')
    op.drop_index(op.f('ix_ejercicios_id'), table_name='ejercicios')
    op.drop_table('ejercicios')
    # ### end Alembic commands ###