"""agregar ingresos pendientes

Revision ID: 8e6f88518a5b
Revises: e26660c0214d
Create Date: 2026-08-15 14:55:24.308902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6f88518a5b'
down_revision: Union[str, None] = 'e26660c0214d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos_pendientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('resuelto', sa.Boolean(), nullable=True),
    sa.Column('fecha_creado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingresos_pendientes_id'), 'ingresos_pendientes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingresos_pendientes_id'), table_name='ingresos_pendientes')
    op.drop_table('ingresos_pendientes')
    # ### end Alembic commands ###