"""agregar tabla movimientos_caja

Revision ID: b2360bf1dc2a
Revises: ff80fe1b076b
Create Date: 2026-08-01 22:40:20.464219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2360bf1dc2a'
down_revision: Union[str, None] = 'ff80fe1b076b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_caja_fecha'), 'movimientos_caja', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_caja_id'), 'movimientos_caja', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_caja_id'), table_name='movimientos_caja')
    op.drop_index(op.f('ix_movimientos_caja_fecha'), table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    # ### end Alembic commands ###