"""agregar recordatorio de correo a socios

Revision ID: c1410b78f1ce
Revises: fc197da41ded
Create Date: 2026-08-06 13:58:25.580332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1410b78f1ce'
down_revision: Union[str, None] = 'fc197da41ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socios', sa.Column('recordatorio_correo_enviado', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socios', 'recordatorio_correo_enviado')
    # ### end Alembic commands ###