"""agregar usuario a comprobantes y compras, agregar actividad

Revision ID: e26660c0214d
Revises: 6d3064f6b4cf
Create Date: 2026-08-14 16:56:09.094269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26660c0214d'
down_revision: Union[str, None] = '6d3064f6b4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras_productos', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'compras_productos', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    op.add_column('comprobantes', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comprobantes', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comprobantes', type_='foreignkey')
    op.drop_column('comprobantes', 'usuario_id')
    op.drop_constraint(None, 'compras_productos', type_='foreignkey')
    op.drop_column('compras_productos', 'usuario_id')
    # ### end Alembic commands ###