"""agregar fecha de nacimiento a socios

Revision ID: f3698796a6f0
Revises: b2360bf1dc2a
Create Date: 2026-08-04 18:44:23.137316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3698796a6f0'
down_revision: Union[str, None] = 'b2360bf1dc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socios', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socios', 'fecha_nacimiento')
    # ### end Alembic commands ###